---
title: "Archive"
author: "Hanne Oberman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, fig.cap = "True effect in the popularity data"}
fits <-
  purrr::map_dfr(
    unique(popcomp$school),
    ~ {
      lm(
        mod,
        data = filter(popcomp, school == .x)
      )
    } %>%
      broom::tidy(conf.int = TRUE, exponentiate = TRUE) %>%
      .[, c("term", "estimate", "conf.low", "conf.high")] %>%
      cbind(school = as.character(.x), .)
  ) %>% filter(term %in% "sex")

n <- popcomp %>% group_by(school) %>% 
  tally() %>% 
  mutate(school = as.character(school))

fits %>% left_join(n, by = "school") %>% 
  ggplot(aes(y = school, x = estimate, linewidth = n)) +
  geom_vline(xintercept = 1, linewidth = 1.5, color = "grey95") +
  geom_linerange(aes(y = school, xmin = conf.low, xmax = conf.high, linewidth = 0.5), position = position_dodge(width = 0.5)) +
  geom_point(shape = 20, position = position_dodge(width = 0.5)) +
  labs(y = "Study", x = "", color = NULL) +
  theme_classic() +
  scale_size(guide = 'none')
```